### ISSUE TITLE
Problem: potentially redundant client context

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain-main#337]
> In the functions TotalSupplyHandlerFn( ) and LiquidSupplyHandlerFn() located in the file x/supply/client/rest/query.go, the client context at a given height (clientCtx) is first obtained by calling the functionParseQueryHeightOrReturnBadRequest(). After performing their respective queries (QueryWithData), these two functions obtain the client context at the height returned, with a call to clientCtx=clientCtx.WithHeight(height)(on lines 34 and 61, respectively). Unless the height returned from QueryWithData() is different, it seems that this operation might be redundant, since the function ParseQueryHeightOrReturnBadRequest() already returns the client context at the given height.

**Comment by devashishdxt** [comment]
I'm not sure about this. While writing the handler functions, I referred to handler functions in `x/bank` module. They seem to do the same thing. https://github.com/cosmos/cosmos-sdk/blob/6a9b0caa57810b6e11332a0edfada28e10d38930/x/bank/client/rest/query.go#L64

**Comment by devashishdxt** [comment]
I'll test if the height returned is different.

**Comment by tomtau** [comment]
ok -- it may be a false positive; just an observation... so will be good to check whether this is needed and perhaps also fix it in Cosmos SDK

**Comment by devashishdxt** [comment]
`ParseQueryHeightOrReturnBadRequest()` parses the request received and checks if it contains `height`. If `height` is present in request, it initialises `clientContext` with given height. Otherwise, it initialises `clientCtx` with `height = 0`. Finally, before sending the response, manually set the `height` in `clientCtx` returned by ABCI call (which is the latest height).

So, I think we can close this issue. @tomtau
